baseurl = ""
languageCode = "es-mx"
title = "CIIE"
canonifyUrls = "true"
theme = "landing-page-hugo"

[params]
    description = "Centro de Investigación de Indicadores Educativos"
    custom_css = ["css/local.css"]

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:contacto@indicadoreseducativos.org"
#[[params.social]]
#    title = "twitter"
#    icon = "twitter"
#    url = "https://twitter.com/SBootstrap"
#[[params.social]]
#    title = "github"
#    icon = "github"
#    url = "https://github.com/IronSummitMedia/startbootstrap"
#[[params.social]]
#    title = "linkedin"
#    icon = "linkedin"
#    url = "http://linkedin.com/in/yourusername"
